# Generated by Django 5.0.6 on 2025-03-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='mobile_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
