# Generated by Django 5.0.6 on 2025-03-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanapplication_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
